package com.ownhabs.app.ui.strings

enum class Lang { EL, EN }

/**
 * Όλα τα ορατά strings της εφαρμογής, σε ένα κεντρικό σημείο. Η εναλλαγή γλώσσας γίνεται
 * εντελώς εντός της εφαρμογής (δεν εξαρτάται από τη γλώσσα συστήματος), μέσω του κουμπιού
 * στις Ρυθμίσεις. Αυτό είναι πιο απλό και αξιόπιστο από πλήρη Android string-resource
 * locale configs για ένα project αυτού του μεγέθους.
 */
data class AppStrings(
    // Γενικά
    val appName: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val back: String,
    val add: String,
    val close: String,

    // Tabbar / Πλοήγηση
    val navHome: String,
    val navBadges: String,
    val navSettings: String,

    // Αρχική
    val homeEmptyTitle: String,
    val homeCompleted: String,
    val homePending: String,
    val homeStreakDays: String,
    val homeMenuEdit: String,
    val homeMenuArchive: String,
    val homeMenuDelete: String,
    val homeDeleteConfirmTitle: String,
    val homeDeleteConfirmText: (String) -> String,
    val homeDeleteConfirmButton: String,
    val homeTimesThisWeek: String,
    val homeTimesThisMonth: String,
    val homeTimesToday: String,

    // Ρυθμίσεις
    val settingsTitle: String,
    val settingsPrivacyBanner: String,
    val settingsExportTitle: String,
    val settingsExportDesc: String,
    val settingsExportButton: String,
    val settingsImportTitle: String,
    val settingsImportDesc: String,
    val settingsImportButton: String,
    val settingsLanguageTitle: String,
    val settingsLanguageDesc: String,

    // Badges
    val badgesTitle: String,
    val badgesLocked: String,

    // History
    val historyCurrentStreak: String,
    val historyBestStreak: String,
    val historyTotal: String,
    val historyHeatmapTitle: String,
    val historyHeatmapHint: String,
    val historyRecentLogs: String,
    val historyStreakFreezeTitle: String,
    val historyStreakFreezeDesc: String,
    val historyStreakFreezeAvailable: (Int, Int) -> String,
    val historyUseFreezeButton: (Int) -> String,
    val historyFrozenDayNotice: String,
    val historyFallbackTitle: String,
    val historyNotesLabel: String,
    val historyValueLabelNumeric: (String) -> String,
    val historyValueLabelBoolean: String,
    val freezeMsgApplied: String,
    val freezeMsgAlreadyLogged: String,
    val freezeMsgAlreadyFrozen: String,
    val freezeMsgLimitReached: String,

    // Add/Edit
    val addEditNewTitle: String,
    val addEditEditTitle: String,
    val addEditFieldTitle: String,
    val addEditFieldDescription: String,
    val addEditIcon: String,
    val addEditColor: String,
    val addEditGoalType: String,
    val addEditGoalBoolean: String,
    val addEditGoalNumeric: String,
    val addEditTargetValue: String,
    val addEditUnit: String,
    val addEditFrequency: String,
    val addEditFrequencyDay: String,
    val addEditFrequencyWeek: String,
    val addEditFrequencyMonth: String,
    val addEditHowManyTimes: String,
    val addEditReminderTime: String,
    val addEditSetTime: String,
    val addEditRemoveTime: String,
    val addEditCreateButton: String,
    val addEditSaveButton: String,
    val addEditArchiveButton: String,

    // Suggestions
    val suggestionsTitle: String,
    val suggestionsIntro: String,
    val suggestionsCustomButton: String,
    val suggestionsNewCategory: String,
    val suggestionsMyCategories: String,
    val suggestionsReadyMade: String,

    // Quick Log dialog (Home tap)
    val quickLogTitle: String,
    val quickLogNotDone: String,
    val quickLogPartial: String,
    val quickLogDoneFull: String,
    val quickLogTodayLabel: String,
    val quickLogSave: String,

    // Κατηγορίες & Custom Templates
    val categoryRename: String,
    val categoryDelete: String,
    val categoryDeleteConfirmTitle: String,
    val categoryDeleteConfirmText: (String) -> String,
    val categoryNewTitle: String,
    val categoryRenameTitle: String,
    val categoryNameLabel: String,
    val categoryCreateButton: String,
    val categoryAddTemplateTooltip: String,
    val templateNewTitle: String,
    val templateEditTitle: String,
    val templateDeleteConfirmTitle: String,
    val templateDeleteConfirmText: String,
    val templateAddButton: String,
    val templateSaveButton: String,
    val templateHintText: String,
    val templatesEmptyInCategory: String,

    // Add/Edit επιπλέον
    val addEditDeleteConfirmTitle: String,
    val addEditDeleteConfirmText: String,
    val addEditDeleteButton: String,

    // Year in Pixels / Recap
    val recapTitle: String,
    val recapShare: String,
    val recapAvgConsistency: (Int) -> String,
    val recapBestStreak: String,
    val recapCompletions: String,
    val recapBadges: String,
    val recapMostConsistent: (String, Int) -> String,
    val recapDetailsHeader: String,
    val recapActiveHabits: String,
    val recapTotalLogs: String,
    val recapBestStreakDetail: (Int, String) -> String,
    val recapBadgesUnlocked: String,
    val recapNoData: String,

    // Έξυπνη υπενθύμιση
    val reminderBooleanText: (String) -> String,
    val reminderNumericText: (String, Int, Int, String) -> String,

    // Ρυθμίσεις — εξαίρεση βελτιστοποίησης μπαταρίας
    val settingsBatteryTitle: String,
    val settingsBatteryDesc: String,
    val settingsBatteryButton: String,
    val settingsBatteryAlreadyOk: String
)

val ElStrings = AppStrings(
    appName = "OwnHabs",
    save = "Αποθήκευση",
    cancel = "Ακύρωση",
    delete = "Διαγραφή",
    edit = "Επεξεργασία",
    back = "Πίσω",
    add = "Προσθήκη",
    close = "Κλείσιμο",

    navHome = "Αρχική",
    navBadges = "Badges",
    navSettings = "Ρυθμίσεις",

    homeEmptyTitle = "Δεν έχεις προσθέσει ακόμα καμία συνήθεια.\nΠάτησε + για να ξεκινήσεις.",
    homeCompleted = "Ολοκληρώθηκε ✓",
    homePending = "Εκκρεμεί",
    homeStreakDays = "ημέρες σερί",
    homeMenuEdit = "Επεξεργασία",
    homeMenuArchive = "Αρχειοθέτηση",
    homeMenuDelete = "Μόνιμη Διαγραφή",
    homeDeleteConfirmTitle = "Μόνιμη διαγραφή;",
    homeDeleteConfirmText = { title -> "Θα διαγραφούν η «$title» και όλο το ιστορικό καταγραφών της. Η ενέργεια δεν αναιρείται." },
    homeDeleteConfirmButton = "Διαγραφή",
    homeTimesThisWeek = "φορές αυτή την εβδομάδα",
    homeTimesThisMonth = "φορές αυτόν τον μήνα",
    homeTimesToday = "σήμερα",

    settingsTitle = "Ρυθμίσεις & Backup",
    settingsPrivacyBanner = "🔒 Η εφαρμογή είναι 100% τοπική. Δεν υπάρχει backend ή cloud server — όλα τα δεδομένα σου μένουν στη συσκευή σου.",
    settingsExportTitle = "Εξαγωγή Δεδομένων",
    settingsExportDesc = "Αποθηκεύει όλες τις συνήθειες, το ιστορικό και τα σήματα σε ένα αρχείο .json.",
    settingsExportButton = "Εξαγωγή σε .json",
    settingsImportTitle = "Εισαγωγή Δεδομένων",
    settingsImportDesc = "Φόρτωσε ένα αρχείο .json από άλλη συσκευή ή παλιό backup.",
    settingsImportButton = "Επιλογή αρχείου .json",
    settingsLanguageTitle = "Γλώσσα",
    settingsLanguageDesc = "Επίλεξε τη γλώσσα της εφαρμογής.",

    badgesTitle = "Σήματα (Badges)",
    badgesLocked = "Κλειδωμένο",

    historyCurrentStreak = "Τρέχον Σερί",
    historyBestStreak = "Καλύτερο Σερί",
    historyTotal = "Σύνολο",
    historyHeatmapTitle = "Πλέγμα Συνέπειας (52 εβδομάδες)",
    historyHeatmapHint = "Πάτησε σε οποιαδήποτε ημέρα για καταγραφή, διόρθωση ή streak freeze. ❄ = παγωμένη ημέρα.",
    historyRecentLogs = "Πρόσφατες Καταγραφές",
    historyStreakFreezeTitle = "Streak Freeze",
    historyStreakFreezeDesc = "Καλύπτει μία χαμένη ημέρα ώστε να μη σπάσει το σερί σου.",
    historyStreakFreezeAvailable = { left, total -> "$left/$total διαθέσιμο" },
    historyUseFreezeButton = { left -> "Χρήση Streak Freeze ($left διαθέσιμο)" },
    historyFrozenDayNotice = "🧊 Αυτή η ημέρα είναι παγωμένη — το σερί σου προστατεύεται.",
    historyFallbackTitle = "Ιστορικό",
    historyNotesLabel = "Σημειώσεις",
    historyValueLabelNumeric = { unit -> "Τιμή ($unit)" },
    historyValueLabelBoolean = "1 = ολοκληρώθηκε, 0 = όχι",
    freezeMsgApplied = "🧊 Το σερί προστατεύτηκε για αυτή την ημέρα.",
    freezeMsgAlreadyLogged = "Η ημέρα έχει ήδη καταγραφή.",
    freezeMsgAlreadyFrozen = "Έχει ήδη εφαρμοστεί freeze σε αυτή την ημέρα.",
    freezeMsgLimitReached = "Έχεις χρησιμοποιήσει το όριο freeze για αυτόν τον μήνα.",

    addEditNewTitle = "Νέα Συνήθεια",
    addEditEditTitle = "Επεξεργασία Συνήθειας",
    addEditFieldTitle = "Τίτλος",
    addEditFieldDescription = "Περιγραφή (προαιρετικό)",
    addEditIcon = "Εικονίδιο",
    addEditColor = "Χρώμα",
    addEditGoalType = "Τύπος Στόχου",
    addEditGoalBoolean = "Ναι / Όχι",
    addEditGoalNumeric = "Ποσοτικός Στόχος",
    addEditTargetValue = "Τιμή Στόχου",
    addEditUnit = "Μονάδα",
    addEditFrequency = "Συχνότητα",
    addEditFrequencyDay = "Ημέρα",
    addEditFrequencyWeek = "Εβδομάδα",
    addEditFrequencyMonth = "Μήνας",
    addEditHowManyTimes = "Πόσες φορές:",
    addEditReminderTime = "Ώρα Υπενθύμισης",
    addEditSetTime = "Ορισμός ώρας",
    addEditRemoveTime = "Κατάργηση",
    addEditCreateButton = "Δημιουργία Συνήθειας",
    addEditSaveButton = "Αποθήκευση Αλλαγών",
    addEditArchiveButton = "Αρχειοθέτηση",

    suggestionsTitle = "Νέα Συνήθεια",
    suggestionsIntro = "Διάλεξε μια έτοιμη πρόταση για γρήγορη έναρξη, ή φτιάξε τη δική σου συνήθεια από το μηδέν.",
    suggestionsCustomButton = "Δημιουργία Προσαρμοσμένης Συνήθειας",
    suggestionsNewCategory = "Νέα Κατηγορία",
    suggestionsMyCategories = "Οι Κατηγορίες μου",
    suggestionsReadyMade = "Έτοιμες Προτάσεις",

    quickLogTitle = "Πόσο έγινε σήμερα;",
    quickLogNotDone = "❌ Δεν έγινε",
    quickLogPartial = "🟡 Εν μέρει",
    quickLogDoneFull = "✅ Έγινε πλήρως",
    quickLogTodayLabel = "Σήμερα",
    quickLogSave = "Αποθήκευση",

    categoryRename = "Μετονομασία",
    categoryDelete = "Διαγραφή Κατηγορίας",
    categoryDeleteConfirmTitle = "Διαγραφή κατηγορίας;",
    categoryDeleteConfirmText = { name -> "Θα διαγραφούν η κατηγορία «$name» και όλες οι προτάσεις μέσα της. Δεν επηρεάζει συνήθειες που έχεις ήδη δημιουργήσει." },
    categoryNewTitle = "Νέα Κατηγορία",
    categoryRenameTitle = "Μετονομασία Κατηγορίας",
    categoryNameLabel = "Όνομα (π.χ. Κατοικίδιο)",
    categoryCreateButton = "Δημιουργία",
    categoryAddTemplateTooltip = "Προσθήκη πρότασης",
    templateNewTitle = "Νέα Πρόταση",
    templateEditTitle = "Επεξεργασία Πρότασης",
    templateDeleteConfirmTitle = "Διαγραφή πρότασης;",
    templateDeleteConfirmText = "Θα αφαιρεθεί μόνιμα από την κατηγορία σου. Δεν επηρεάζει τις συνήθειες που έχεις ήδη δημιουργήσει από αυτήν.",
    templateAddButton = "Προσθήκη στην Κατηγορία",
    templateSaveButton = "Αποθήκευση Αλλαγών",
    templateHintText = "Αυτή είναι μια πρόταση, όχι μια ενεργή συνήθεια — θα εμφανίζεται στη λίστα προτάσεων όταν πατάς «+».",
    templatesEmptyInCategory = "Δεν έχεις προσθέσει ακόμα προτάσεις εδώ.",

    addEditDeleteConfirmTitle = "Μόνιμη διαγραφή;",
    addEditDeleteConfirmText = "Θα διαγραφούν η συνήθεια και όλο το ιστορικό καταγραφών της. Η ενέργεια δεν αναιρείται.",
    addEditDeleteButton = "Διαγραφή",

    recapTitle = "Το Έτος σου σε Pixels",
    recapShare = "Κοινοποίηση",
    recapAvgConsistency = { pct -> "$pct% μέση συνέπεια" },
    recapBestStreak = "καλύτερο σερί",
    recapCompletions = "καταγραφές",
    recapBadges = "badges",
    recapMostConsistent = { title, pct -> "Πιο συνεπής συνήθεια: $title ($pct%)" },
    recapDetailsHeader = "Λεπτομέρειες",
    recapActiveHabits = "Ενεργές συνήθειες",
    recapTotalLogs = "Σύνολο καταγραφών",
    recapBestStreakDetail = { days, title -> "$days ημέρες («$title»)" },
    recapBadgesUnlocked = "Badges που ξεκλειδώθηκαν",
    recapNoData = "—",

    reminderBooleanText = { title -> "Ώρα για: $title" },
    reminderNumericText = { title, done, target, unit -> "$title: $done/$target $unit — έλα να το ολοκληρώσεις" },

    settingsBatteryTitle = "Αξιοπιστία Ειδοποιήσεων",
    settingsBatteryDesc = "Ορισμένες συσκευές (ειδικά Xiaomi, Huawei, Samsung) περιορίζουν εφαρμογές στο παρασκήνιο για εξοικονόμηση μπαταρίας, με αποτέλεσμα να χάνονται υπενθυμίσεις. Εξαίρεσε το OwnHabs από τη βελτιστοποίηση μπαταρίας για να το αποφύγεις.",
    settingsBatteryButton = "Άνοιγμα Ρυθμίσεων Μπαταρίας",
    settingsBatteryAlreadyOk = "✓ Η εφαρμογή είναι ήδη εξαιρεμένη"
)

val EnStrings = AppStrings(
    appName = "OwnHabs",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    back = "Back",
    add = "Add",
    close = "Close",

    navHome = "Home",
    navBadges = "Badges",
    navSettings = "Settings",

    homeEmptyTitle = "You haven't added any habits yet.\nTap + to get started.",
    homeCompleted = "Completed ✓",
    homePending = "Pending",
    homeStreakDays = "day streak",
    homeMenuEdit = "Edit",
    homeMenuArchive = "Archive",
    homeMenuDelete = "Delete Permanently",
    homeDeleteConfirmTitle = "Delete permanently?",
    homeDeleteConfirmText = { title -> "\"$title\" and all of its log history will be deleted. This can't be undone." },
    homeDeleteConfirmButton = "Delete",
    homeTimesThisWeek = "times this week",
    homeTimesThisMonth = "times this month",
    homeTimesToday = "today",

    settingsTitle = "Settings & Backup",
    settingsPrivacyBanner = "🔒 This app is 100% local. There's no backend or cloud server — all your data stays on your device.",
    settingsExportTitle = "Export Data",
    settingsExportDesc = "Saves all your habits, history, and badges to a .json file.",
    settingsExportButton = "Export to .json",
    settingsImportTitle = "Import Data",
    settingsImportDesc = "Load a .json file from another device or an old backup.",
    settingsImportButton = "Choose .json file",
    settingsLanguageTitle = "Language",
    settingsLanguageDesc = "Choose the app's language.",

    badgesTitle = "Badges",
    badgesLocked = "Locked",

    historyCurrentStreak = "Current Streak",
    historyBestStreak = "Best Streak",
    historyTotal = "Total",
    historyHeatmapTitle = "Consistency Grid (52 weeks)",
    historyHeatmapHint = "Tap any day to log, edit, or apply a streak freeze. ❄ = frozen day.",
    historyRecentLogs = "Recent Logs",
    historyStreakFreezeTitle = "Streak Freeze",
    historyStreakFreezeDesc = "Covers one missed day so your streak doesn't break.",
    historyStreakFreezeAvailable = { left, total -> "$left/$total available" },
    historyUseFreezeButton = { left -> "Use Streak Freeze ($left available)" },
    historyFrozenDayNotice = "🧊 This day is frozen — your streak is protected.",
    historyFallbackTitle = "History",
    historyNotesLabel = "Notes",
    historyValueLabelNumeric = { unit -> "Value ($unit)" },
    historyValueLabelBoolean = "1 = done, 0 = not done",
    freezeMsgApplied = "🧊 Your streak is protected for this day.",
    freezeMsgAlreadyLogged = "This day already has a log.",
    freezeMsgAlreadyFrozen = "A freeze has already been applied to this day.",
    freezeMsgLimitReached = "You've used your freeze limit for this month.",

    addEditNewTitle = "New Habit",
    addEditEditTitle = "Edit Habit",
    addEditFieldTitle = "Title",
    addEditFieldDescription = "Description (optional)",
    addEditIcon = "Icon",
    addEditColor = "Color",
    addEditGoalType = "Goal Type",
    addEditGoalBoolean = "Yes / No",
    addEditGoalNumeric = "Numeric Goal",
    addEditTargetValue = "Target Value",
    addEditUnit = "Unit",
    addEditFrequency = "Frequency",
    addEditFrequencyDay = "Day",
    addEditFrequencyWeek = "Week",
    addEditFrequencyMonth = "Month",
    addEditHowManyTimes = "How many times:",
    addEditReminderTime = "Reminder Time",
    addEditSetTime = "Set time",
    addEditRemoveTime = "Remove",
    addEditCreateButton = "Create Habit",
    addEditSaveButton = "Save Changes",
    addEditArchiveButton = "Archive",

    suggestionsTitle = "New Habit",
    suggestionsIntro = "Pick a ready-made suggestion for a quick start, or build your own habit from scratch.",
    suggestionsCustomButton = "Create Custom Habit",
    suggestionsNewCategory = "New Category",
    suggestionsMyCategories = "My Categories",
    suggestionsReadyMade = "Ready-Made Suggestions",

    quickLogTitle = "How much did you do today?",
    quickLogNotDone = "❌ Not done",
    quickLogPartial = "🟡 Partially",
    quickLogDoneFull = "✅ Fully done",
    quickLogTodayLabel = "Today",
    quickLogSave = "Save",

    categoryRename = "Rename",
    categoryDelete = "Delete Category",
    categoryDeleteConfirmTitle = "Delete category?",
    categoryDeleteConfirmText = { name -> "\"$name\" and all suggestions inside it will be deleted. Habits you've already created aren't affected." },
    categoryNewTitle = "New Category",
    categoryRenameTitle = "Rename Category",
    categoryNameLabel = "Name (e.g. Pet)",
    categoryCreateButton = "Create",
    categoryAddTemplateTooltip = "Add suggestion",
    templateNewTitle = "New Suggestion",
    templateEditTitle = "Edit Suggestion",
    templateDeleteConfirmTitle = "Delete suggestion?",
    templateDeleteConfirmText = "It will be permanently removed from your category. Habits already created from it aren't affected.",
    templateAddButton = "Add to Category",
    templateSaveButton = "Save Changes",
    templateHintText = "This is a suggestion, not an active habit — it'll show up in the suggestions list when you tap \"+\".",
    templatesEmptyInCategory = "You haven't added any suggestions here yet.",

    addEditDeleteConfirmTitle = "Delete permanently?",
    addEditDeleteConfirmText = "The habit and all of its log history will be deleted. This can't be undone.",
    addEditDeleteButton = "Delete",

    recapTitle = "Your Year in Pixels",
    recapShare = "Share",
    recapAvgConsistency = { pct -> "$pct% average consistency" },
    recapBestStreak = "best streak",
    recapCompletions = "logs",
    recapBadges = "badges",
    recapMostConsistent = { title, pct -> "Most consistent habit: $title ($pct%)" },
    recapDetailsHeader = "Details",
    recapActiveHabits = "Active habits",
    recapTotalLogs = "Total logs",
    recapBestStreakDetail = { days, title -> "$days days (\"$title\")" },
    recapBadgesUnlocked = "Badges unlocked",
    recapNoData = "—",

    reminderBooleanText = { title -> "Time for: $title" },
    reminderNumericText = { title, done, target, unit -> "$title: $done/$target $unit — come finish it off" },

    settingsBatteryTitle = "Notification Reliability",
    settingsBatteryDesc = "Some devices (especially Xiaomi, Huawei, Samsung) restrict background apps to save battery, which can cause reminders to be missed. Exempt OwnHabs from battery optimization to avoid this.",
    settingsBatteryButton = "Open Battery Settings",
    settingsBatteryAlreadyOk = "✓ App is already exempted"
)

fun stringsFor(lang: Lang): AppStrings = when (lang) { Lang.EL -> ElStrings; Lang.EN -> EnStrings }
